"""Dash viewer for Notebook 07b PCA dislocation artifacts.

The app intentionally reads precomputed CSV artifacts only. Notebook 07b owns
the methodology and produces the PCA, momentum, regime, and diagnostic outputs.
"""

from pathlib import Path

import pandas as pd
import plotly.express as px
import plotly.graph_objects as go
from dash import Dash, Input, Output, dcc, html, dash_table


APP_TITLE = "PCA Dislocation & Macro-Aware Momentum Dashboard"
APP_SUBTITLE = (
    "Interactive viewer over Notebook 07b artifacts. Diagnostics only — no trading "
    "recommendations."
)
DISCLAIMER = (
    "This dashboard reads deterministic artifacts generated by Notebook 07b. It does "
    "not recompute PCA, momentum, regimes, or diagnostic labels. Outputs are research "
    "diagnostics, not buy/sell recommendations or portfolio-construction signals."
)
ARTIFACT_ONLY_NOTE = (
    "Reads saved artifacts only; does not recompute PCA, momentum, regimes, residuals, "
    "or diagnostic labels."
)
GAP_NOTE = (
    "These gaps are explicit by design. The dashboard does not fabricate positioning "
    "data or macro-support scores."
)

ARTIFACT_DIR = Path("results/notebook_07b")
ARTIFACT_FILES = {
    "scorecard": "pca_dislocation_scorecard.csv",
    "dislocation_scores": "pca_dislocation_scores.csv",
    "momentum_scores": "momentum_scores.csv",
    "macro_regime_overlay": "macro_regime_overlay.csv",
    "rolling_pca_diagnostics": "rolling_pca_reconstruction_diagnostics.csv",
    "methodology_gap_table": "methodology_gap_table.csv",
}
REQUIRED_COLUMNS = {
    "scorecard": {
        "asset",
        "asset_class",
        "pca_dislocation_z",
        "momentum_score",
        "diagnostic_label",
    },
    "dislocation_scores": {"date", "asset", "pca_dislocation_z"},
    "rolling_pca_diagnostics": {"date"},
    "methodology_gap_table": {
        "methodology_element",
        "availability_in_repo",
        "07b_v1_treatment",
    },
}
SCORECARD_COLUMNS = [
    "asset",
    "asset_class",
    "pca_dislocation_z",
    "dislocation_bucket",
    "momentum_score",
    "momentum_bucket",
    "dominant_regime",
    "macro_context",
    "diagnostic_label",
    "abs_dislocation_rank",
]

PAGE_STYLE = {
    "backgroundColor": "#eef2f6",
    "color": "#1f2937",
    "fontFamily": "Inter, -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif",
    "minHeight": "100vh",
    "padding": "28px",
}
SHELL_STYLE = {"maxWidth": "1440px", "margin": "0 auto"}
CARD_STYLE = {
    "backgroundColor": "#ffffff",
    "border": "1px solid #d9e0e8",
    "borderRadius": "8px",
    "boxShadow": "0 10px 28px rgba(15, 23, 42, 0.06)",
    "padding": "20px",
    "marginBottom": "20px",
}
HEADER_STYLE = {
    **CARD_STYLE,
    "backgroundColor": "#0f1f33",
    "border": "1px solid #20344f",
    "boxShadow": "0 18px 36px rgba(15, 31, 51, 0.16)",
    "padding": "24px 26px",
}
SECTION_TITLE_STYLE = {
    "fontSize": "16px",
    "fontWeight": 650,
    "margin": "0 0 14px",
    "color": "#111827",
}
CONTROL_GRID_STYLE = {
    "display": "grid",
    "gridTemplateColumns": "repeat(4, minmax(180px, 1fr))",
    "gap": "16px",
    "alignItems": "end",
}
LABEL_STYLE = {
    "display": "block",
    "fontSize": "11px",
    "fontWeight": 700,
    "color": "#607083",
    "marginBottom": "6px",
    "textTransform": "uppercase",
    "letterSpacing": "0",
}
GRAPH_CONFIG = {"displaylogo": False, "responsive": True}
NEUTRAL_TEMPLATE = "plotly_white"
PALETTE = {
    "navy": "#10233f",
    "slate": "#475569",
    "muted_slate": "#64748b",
    "blue": "#2f6fbb",
    "blue_soft": "#dceafd",
    "amber": "#b7791f",
    "amber_soft": "#fff4dc",
    "rose": "#b4535f",
    "rose_soft": "#fbe7ea",
    "gold": "#9a7b24",
    "teal": "#1f766e",
    "grid": "#e6ebf1",
}
CHART_COLOR_SEQUENCE = [
    PALETTE["blue"],
    PALETTE["rose"],
    PALETTE["teal"],
    PALETTE["gold"],
    PALETTE["muted_slate"],
    "#5b6f95",
    "#8a6f3d",
]
CHART_LAYOUT = {
    "template": NEUTRAL_TEMPLATE,
    "paper_bgcolor": "white",
    "plot_bgcolor": "white",
    "font": {"family": PAGE_STYLE["fontFamily"], "size": 12, "color": "#1f2937"},
    "legend": {
        "orientation": "h",
        "yanchor": "bottom",
        "y": 1.02,
        "xanchor": "right",
        "x": 1,
        "font": {"size": 11},
        "title": {"font": {"size": 11}},
    },
    "title": {"font": {"size": 16, "color": "#111827"}, "x": 0.01, "xanchor": "left"},
}


def find_repo_root(start: Path | None = None) -> Path:
    """Find the repository root from this file path or the current working tree."""
    current = (start or Path(__file__)).resolve()
    if current.is_file():
        current = current.parent

    for candidate in [current, *current.parents]:
        if (candidate / ".git").exists() and (candidate / "results").exists():
            return candidate
    return Path(__file__).resolve().parents[1]


def validate_columns(
    frame: pd.DataFrame, required_columns: set[str], artifact_name: str
) -> list[str]:
    """Return validation errors for required columns without raising tracebacks."""
    missing = sorted(required_columns - set(frame.columns))
    if not missing:
        return []
    return [f"{artifact_name} is missing required columns: {', '.join(missing)}"]


def load_artifacts(repo_root: Path | None = None) -> dict[str, pd.DataFrame | list[str]]:
    """Load Notebook 07b artifacts and collect user-facing validation errors."""
    root = repo_root or find_repo_root()
    base = root / ARTIFACT_DIR
    artifacts: dict[str, pd.DataFrame | list[str]] = {"_errors": []}
    errors: list[str] = []

    for key, filename in ARTIFACT_FILES.items():
        path = base / filename
        if not path.exists():
            errors.append(f"Missing required artifact: {path.relative_to(root)}")
            artifacts[key] = pd.DataFrame()
            continue

        try:
            frame = pd.read_csv(path)
        except Exception as exc:  # pragma: no cover - depends on local file damage
            errors.append(f"Could not read {path.relative_to(root)}: {exc}")
            artifacts[key] = pd.DataFrame()
            continue

        if "date" in frame.columns:
            frame["date"] = pd.to_datetime(frame["date"], errors="coerce")
        if key in REQUIRED_COLUMNS:
            errors.extend(validate_columns(frame, REQUIRED_COLUMNS[key], filename))
        artifacts[key] = frame

    artifacts["_errors"] = errors
    return artifacts


def latest_top_abs_dislocation_assets(scorecard: pd.DataFrame, n: int = 5) -> list[str]:
    """Select default assets from the latest scorecard by absolute dislocation."""
    if scorecard.empty or not {"asset", "pca_dislocation_z"}.issubset(scorecard.columns):
        return []

    frame = scorecard.copy()
    frame["_abs_dislocation"] = frame["pca_dislocation_z"].abs()
    return (
        frame.sort_values("_abs_dislocation", ascending=False)["asset"]
        .dropna()
        .astype(str)
        .head(n)
        .tolist()
    )


def _dropdown_options(values: pd.Series | list[str]) -> list[dict[str, str]]:
    unique_values = pd.Series(values).dropna().astype(str).sort_values().unique()
    return [{"label": value, "value": value} for value in unique_values]


def _all_values(values: pd.Series | list[str]) -> list[str]:
    return [option["value"] for option in _dropdown_options(values)]


def _apply_chart_layout(
    fig: go.Figure,
    *,
    height: int,
    margin: dict[str, int] | None = None,
    legend: dict[str, object] | None = None,
) -> go.Figure:
    layout = {
        **CHART_LAYOUT,
        "height": height,
        "margin": margin or {"l": 52, "r": 28, "t": 62, "b": 52},
    }
    if legend:
        layout["legend"] = {**CHART_LAYOUT["legend"], **legend}
    fig.update_layout(**layout)
    fig.update_xaxes(
        showgrid=True,
        gridcolor=PALETTE["grid"],
        zerolinecolor="#cbd5e1",
        linecolor="#cbd5e1",
        tickfont={"size": 11},
        title_font={"size": 12},
    )
    fig.update_yaxes(
        showgrid=True,
        gridcolor=PALETTE["grid"],
        zerolinecolor="#cbd5e1",
        linecolor="#cbd5e1",
        tickfont={"size": 11},
        title_font={"size": 12},
    )
    return fig


def _empty_figure(title: str, message: str) -> go.Figure:
    fig = go.Figure()
    fig.update_layout(
        title=title,
        annotations=[
            {
                "text": message,
                "xref": "paper",
                "yref": "paper",
                "x": 0.5,
                "y": 0.5,
                "showarrow": False,
                "font": {"color": "#52616f", "size": 13},
            }
        ],
        xaxis={"visible": False},
        yaxis={"visible": False},
    )
    return _apply_chart_layout(fig, height=360)


def _format_date(value: object) -> str:
    if pd.isna(value):
        return "n/a"
    timestamp = pd.to_datetime(value, errors="coerce")
    if pd.isna(timestamp):
        return str(value)
    return timestamp.strftime("%Y-%m-%d")


def _format_dislocation_asset(row: pd.Series | None) -> tuple[str, str]:
    if row is None or row.empty:
        return "n/a", "diagnostic only"
    asset = str(row.get("asset", "n/a"))
    value = pd.to_numeric(pd.Series([row.get("pca_dislocation_z")]), errors="coerce").iloc[0]
    detail = "diagnostic only" if pd.isna(value) else f"z-score {value:.2f}"
    return asset, detail


def _build_kpi_items(scorecard: pd.DataFrame) -> list[dict[str, str]]:
    if scorecard.empty:
        return [
            {"label": "Latest date", "value": "n/a", "detail": "artifact viewer"},
            {"label": "Assets", "value": "0", "detail": "scorecard rows"},
            {"label": "Dominant regime", "value": "n/a", "detail": "diagnostic only"},
            {"label": "Positive dislocation", "value": "n/a", "detail": "diagnostic only"},
            {"label": "Negative dislocation", "value": "n/a", "detail": "diagnostic only"},
            {"label": "Median absolute dislocation", "value": "n/a", "detail": "z-score"},
        ]

    latest_date = (
        _format_date(scorecard["date"].max()) if "date" in scorecard.columns else "latest"
    )
    asset_count = scorecard["asset"].nunique() if "asset" in scorecard.columns else len(scorecard)
    regime = "n/a"
    if "dominant_regime" in scorecard.columns and not scorecard["dominant_regime"].dropna().empty:
        regime = str(scorecard["dominant_regime"].dropna().astype(str).mode().iloc[0])

    z_scores = (
        pd.to_numeric(scorecard["pca_dislocation_z"], errors="coerce")
        if "pca_dislocation_z" in scorecard.columns
        else pd.Series(dtype="float64")
    )
    positive_row = scorecard.loc[z_scores.idxmax()] if not z_scores.dropna().empty else None
    negative_row = scorecard.loc[z_scores.idxmin()] if not z_scores.dropna().empty else None
    positive_asset, positive_detail = _format_dislocation_asset(positive_row)
    negative_asset, negative_detail = _format_dislocation_asset(negative_row)
    median_abs = z_scores.abs().median()
    median_abs_text = "n/a" if pd.isna(median_abs) else f"{median_abs:.2f}"

    return [
        {"label": "Latest date", "value": latest_date, "detail": "scorecard snapshot"},
        {"label": "Assets", "value": f"{asset_count}", "detail": "loaded from artifacts"},
        {"label": "Dominant regime", "value": regime, "detail": "diagnostic only"},
        {"label": "Positive dislocation", "value": positive_asset, "detail": positive_detail},
        {"label": "Negative dislocation", "value": negative_asset, "detail": negative_detail},
        {
            "label": "Median absolute dislocation",
            "value": median_abs_text,
            "detail": "z-score",
        },
    ]


def _kpi_cards(scorecard: pd.DataFrame) -> html.Div:
    return html.Div(
        style={
            "display": "grid",
            "gridTemplateColumns": "repeat(6, minmax(145px, 1fr))",
            "gap": "12px",
            "marginBottom": "20px",
        },
        children=[
            html.Div(
                style={
                    "backgroundColor": "#ffffff",
                    "border": "1px solid #d9e0e8",
                    "borderRadius": "8px",
                    "padding": "14px 15px",
                    "boxShadow": "0 6px 18px rgba(15, 23, 42, 0.05)",
                    "minHeight": "92px",
                },
                children=[
                    html.Div(
                        item["label"],
                        style={
                            "fontSize": "11px",
                            "fontWeight": 700,
                            "color": "#607083",
                            "textTransform": "uppercase",
                            "letterSpacing": "0",
                            "marginBottom": "8px",
                        },
                    ),
                    html.Div(
                        item["value"],
                        style={
                            "fontSize": "19px",
                            "fontWeight": 700,
                            "lineHeight": "1.2",
                            "color": "#10233f",
                            "wordBreak": "break-word",
                        },
                    ),
                    html.Div(
                        item["detail"],
                        style={"fontSize": "12px", "color": "#64748b", "marginTop": "6px"},
                    ),
                ],
            )
            for item in _build_kpi_items(scorecard)
        ],
    )



def filter_scorecard(
    scorecard: pd.DataFrame,
    asset_classes: list[str] | None,
    regimes: list[str] | None,
    diagnostic_labels: list[str] | None,
) -> pd.DataFrame:
    """Apply viewer filters to the latest scorecard artifact."""
    frame = scorecard.copy()
    if frame.empty:
        return frame

    if asset_classes and "asset_class" in frame.columns:
        frame = frame[frame["asset_class"].astype(str).isin(asset_classes)]
    if regimes and "dominant_regime" in frame.columns:
        frame = frame[frame["dominant_regime"].astype(str).isin(regimes)]
    if diagnostic_labels and "diagnostic_label" in frame.columns:
        frame = frame[frame["diagnostic_label"].astype(str).isin(diagnostic_labels)]
    return frame


def _select_top_abs(frame: pd.DataFrame, top_n: int) -> pd.DataFrame:
    if frame.empty or "pca_dislocation_z" not in frame.columns:
        return frame
    selected = frame.assign(_abs_dislocation=frame["pca_dislocation_z"].abs())
    return selected.sort_values("_abs_dislocation", ascending=False).head(top_n)


def make_dislocation_bar(scorecard: pd.DataFrame, top_n: int) -> go.Figure:
    """Build latest PCA dislocation bar chart from the scorecard artifact."""
    frame = _select_top_abs(scorecard, top_n)
    title = "Latest PCA Dislocation Z-Scores"
    if frame.empty:
        return _empty_figure(title, "No scorecard rows match the current filters.")

    frame = frame.copy()
    frame["_direction"] = frame["pca_dislocation_z"].apply(
        lambda value: "Positive dislocation"
        if value >= 2
        else "Negative dislocation"
        if value <= -2
        else "Diagnostic only"
    )
    color_map = {
        "Positive dislocation": PALETTE["blue"],
        "Negative dislocation": PALETTE["rose"],
        "Diagnostic only": PALETTE["muted_slate"],
    }

    fig = px.bar(
        frame.sort_values("pca_dislocation_z", ascending=True),
        x="asset",
        y="pca_dislocation_z",
        color="_direction",
        hover_data=[col for col in SCORECARD_COLUMNS if col in frame.columns],
        title=title,
        template=NEUTRAL_TEMPLATE,
        color_discrete_map=color_map,
    )
    fig.add_hline(y=2, line_dash="dash", line_color=PALETTE["slate"], opacity=0.62)
    fig.add_hline(y=-2, line_dash="dash", line_color=PALETTE["slate"], opacity=0.62)
    fig.update_traces(
        marker_line_width=0,
        hovertemplate="<b>%{x}</b><br>PCA dislocation z-score: %{y:.2f}<extra></extra>",
    )
    fig.update_layout(
        legend_title_text="",
        bargap=0.24,
    )
    fig.update_xaxes(title_text="", tickangle=-35)
    fig.update_yaxes(title_text="PCA dislocation z-score", zeroline=True)
    return _apply_chart_layout(fig, height=440, margin={"l": 54, "r": 24, "t": 62, "b": 104})


def make_dislocation_momentum_scatter(scorecard: pd.DataFrame) -> go.Figure:
    """Build dislocation-vs-momentum diagnostic scatter from scorecard artifact."""
    title = "Dislocation vs Momentum Confirmation"
    required = {"asset", "pca_dislocation_z", "momentum_score"}
    if scorecard.empty or not required.issubset(scorecard.columns):
        return _empty_figure(title, "Required scorecard columns are unavailable.")

    color_col = "diagnostic_label" if "diagnostic_label" in scorecard.columns else "asset_class"
    hover_cols = [
        col
        for col in [
            "asset",
            "asset_class",
            "dominant_regime",
            "dislocation_bucket",
            "momentum_bucket",
            "diagnostic_label",
        ]
        if col in scorecard.columns
    ]
    fig = px.scatter(
        scorecard,
        x="pca_dislocation_z",
        y="momentum_score",
        color=color_col if color_col in scorecard.columns else None,
        hover_name="asset",
        hover_data=hover_cols,
        title=title,
        template=NEUTRAL_TEMPLATE,
        color_discrete_sequence=CHART_COLOR_SEQUENCE,
    )
    fig.add_vline(x=0, line_dash="dash", line_color=PALETTE["slate"], opacity=0.62)
    fig.add_hline(y=0, line_dash="dash", line_color=PALETTE["slate"], opacity=0.62)
    fig.update_traces(
        marker={"size": 10, "line": {"width": 0.8, "color": "#ffffff"}, "opacity": 0.92},
        hovertemplate="<b>%{customdata[0]}</b><br>Dislocation z-score: %{x:.2f}<br>Momentum score: %{y:.2f}<extra></extra>",
    )
    fig.update_layout(
        legend_title_text=color_col.replace("_", " ").title(),
    )
    fig.update_xaxes(title_text="PCA dislocation z-score")
    fig.update_yaxes(title_text="Momentum score")
    return _apply_chart_layout(fig, height=440, margin={"l": 54, "r": 24, "t": 62, "b": 54})


def make_dislocation_timeseries(
    dislocation_scores: pd.DataFrame, selected_assets: list[str] | None
) -> go.Figure:
    """Build selected asset dislocation history from the precomputed time series."""
    title = "Selected Asset PCA Dislocation History"
    required = {"date", "asset", "pca_dislocation_z"}
    if dislocation_scores.empty or not required.issubset(dislocation_scores.columns):
        return _empty_figure(title, "Required dislocation history columns are unavailable.")
    if not selected_assets:
        return _empty_figure(title, "Select at least one asset to display history.")

    frame = dislocation_scores[
        dislocation_scores["asset"].astype(str).isin([str(asset) for asset in selected_assets])
    ].copy()
    if frame.empty:
        return _empty_figure(title, "No dislocation history is available for selected assets.")

    fig = px.line(
        frame.sort_values("date"),
        x="date",
        y="pca_dislocation_z",
        color="asset",
        title=title,
        template=NEUTRAL_TEMPLATE,
        color_discrete_sequence=CHART_COLOR_SEQUENCE,
    )
    for y_value, width in [(2, 1), (0, 1.2), (-2, 1)]:
        fig.add_hline(
            y=y_value,
            line_dash="dash" if y_value else "solid",
            line_color=PALETTE["slate"],
            line_width=width,
            opacity=0.6,
        )
    fig.update_traces(line={"width": 1.7}, opacity=0.92)
    fig.update_layout(legend_title_text="Asset")
    fig.update_xaxes(title_text="")
    fig.update_yaxes(title_text="PCA dislocation z-score")
    return _apply_chart_layout(
        fig,
        height=500,
        margin={"l": 54, "r": 28, "t": 62, "b": 58},
        legend={"y": -0.24, "x": 0, "xanchor": "left", "yanchor": "top"},
    )


def make_rolling_pca_diagnostics(diagnostics: pd.DataFrame) -> go.Figure:
    """Build rolling PCA diagnostics from Notebook 07b reconstruction artifacts."""
    title = "Rolling PCA Reconstruction Diagnostics"
    if diagnostics.empty or "date" not in diagnostics.columns:
        return _empty_figure(title, "Rolling PCA diagnostic artifact is unavailable.")

    cumulative_col = "pc1_pc5_cumulative_explained_variance_ratio"
    error_cols = [
        col
        for col in ["reconstruction_rmse", "reconstruction_mae", "reconstruction_error"]
        if col in diagnostics.columns
    ]
    has_cumulative = cumulative_col in diagnostics.columns
    if not has_cumulative and not error_cols:
        return _empty_figure(title, "No supported diagnostic series are present.")

    frame = diagnostics.sort_values("date").copy()
    fig = go.Figure()
    if has_cumulative:
        fig.add_trace(
            go.Scatter(
                x=frame["date"],
                y=frame[cumulative_col],
                mode="lines",
                name="PC1-PC5 cumulative explained variance",
                line={"color": PALETTE["blue"], "width": 2},
                yaxis="y",
            )
        )
    for idx, col in enumerate(error_cols):
        fig.add_trace(
            go.Scatter(
                x=frame["date"],
                y=frame[col],
                mode="lines",
                name=col.replace("_", " ").title(),
                line={
                    "color": [PALETTE["muted_slate"], PALETTE["teal"], PALETTE["gold"]][
                        idx % 3
                    ],
                    "width": 1.8,
                },
                yaxis="y2" if has_cumulative else "y",
            )
        )

    layout = {
        "title": title,
        "xaxis": {"title": ""},
    }
    if has_cumulative and error_cols:
        layout.update(
            {
                "yaxis": {"title": "Cumulative explained variance"},
                "yaxis2": {
                    "title": "Reconstruction error",
                    "overlaying": "y",
                    "side": "right",
                    "showgrid": False,
                },
            }
        )
    else:
        layout["yaxis"] = {
            "title": "Cumulative explained variance"
            if has_cumulative
            else "Reconstruction error"
        }
    fig.update_layout(**layout)
    return _apply_chart_layout(
        fig,
        height=470,
        margin={"l": 58, "r": 72, "t": 62, "b": 68},
        legend={"y": -0.22, "x": 0, "xanchor": "left", "yanchor": "top"},
    )


def _data_table_columns(frame: pd.DataFrame) -> list[dict[str, object]]:
    numeric_cols = set(frame.select_dtypes(include="number").columns)
    columns: list[dict[str, object]] = []
    for col in frame.columns:
        column: dict[str, object] = {"name": col, "id": col}
        if col in numeric_cols:
            column.update({"type": "numeric", "format": {"specifier": ".2f"}})
        columns.append(column)
    return columns


def _scorecard_table(frame: pd.DataFrame) -> dash_table.DataTable:
    visible_columns = [col for col in SCORECARD_COLUMNS if col in frame.columns]
    table_frame = frame[visible_columns].copy() if visible_columns else frame.copy()
    return dash_table.DataTable(
        id="scorecard-table",
        columns=_data_table_columns(table_frame),
        data=table_frame.to_dict("records"),
        sort_action="native",
        filter_action="native",
        page_action="none",
        fixed_rows={"headers": True},
        fixed_columns={"headers": True, "data": 1},
        style_as_list_view=True,
        style_table={
            "height": "500px",
            "overflowY": "auto",
            "overflowX": "auto",
            "minWidth": "100%",
        },
        style_cell={
            "fontFamily": PAGE_STYLE["fontFamily"],
            "fontSize": "12.5px",
            "padding": "10px 12px",
            "textAlign": "left",
            "minWidth": "125px",
            "maxWidth": "280px",
            "whiteSpace": "normal",
            "height": "auto",
            "lineHeight": "1.35",
        },
        style_cell_conditional=[
            {"if": {"column_id": "asset"}, "minWidth": "125px", "fontWeight": 700},
            {"if": {"column_id": "asset_class"}, "minWidth": "120px"},
            {"if": {"column_id": "pca_dislocation_z"}, "minWidth": "132px", "textAlign": "right"},
            {"if": {"column_id": "momentum_score"}, "minWidth": "132px", "textAlign": "right"},
            {"if": {"column_id": "abs_dislocation_rank"}, "minWidth": "136px", "textAlign": "right"},
            {"if": {"column_id": "dislocation_bucket"}, "minWidth": "150px"},
            {"if": {"column_id": "momentum_bucket"}, "minWidth": "150px"},
            {"if": {"column_id": "dominant_regime"}, "minWidth": "160px"},
            {"if": {"column_id": "macro_context"}, "minWidth": "210px"},
            {"if": {"column_id": "diagnostic_label"}, "minWidth": "280px"},
        ],
        style_header={
            "backgroundColor": "#10233f",
            "fontWeight": 700,
            "color": "#ffffff",
            "border": "1px solid #20344f",
            "fontSize": "11px",
            "textTransform": "uppercase",
            "letterSpacing": "0",
        },
        style_data={"border": "1px solid #e5e7eb", "backgroundColor": "#ffffff"},
        style_data_conditional=[
            {
                "if": {"row_index": "odd"},
                "backgroundColor": "#f8fafc",
            },
            {
                "if": {"filter_query": "{abs_dislocation_rank} <= 5"},
                "backgroundColor": "#fffaf0",
                "borderLeft": f"3px solid {PALETTE['gold']}",
            },
            {
                "if": {"filter_query": "{pca_dislocation_z} >= 2", "column_id": "pca_dislocation_z"},
                "backgroundColor": PALETTE["blue_soft"],
                "color": "#173f70",
                "fontWeight": 700,
            },
            {
                "if": {"filter_query": "{pca_dislocation_z} <= -2", "column_id": "pca_dislocation_z"},
                "backgroundColor": PALETTE["rose_soft"],
                "color": "#7f2f3c",
                "fontWeight": 650,
            },
        ],
    )


def _small_table(frame: pd.DataFrame) -> dash_table.DataTable:
    return dash_table.DataTable(
        columns=_data_table_columns(frame),
        data=frame.to_dict("records"),
        sort_action="native",
        page_action="native",
        page_size=8,
        style_as_list_view=True,
        style_table={"overflowX": "auto"},
        style_cell={
            "fontFamily": PAGE_STYLE["fontFamily"],
            "fontSize": "12.5px",
            "padding": "9px 10px",
            "textAlign": "left",
            "whiteSpace": "normal",
            "height": "auto",
        },
        style_header={
            "backgroundColor": "#f1f5f9",
            "fontWeight": 700,
            "color": "#1f2933",
            "border": "1px solid #d8dee6",
            "fontSize": "11px",
            "textTransform": "uppercase",
            "letterSpacing": "0",
        },
        style_data={"border": "1px solid #e5e7eb"},
    )


def _control(label: str, component: object) -> html.Div:
    return html.Div([html.Label(label, style=LABEL_STYLE), component])


def _error_layout(errors: list[str]) -> html.Div:
    return html.Div(
        style=PAGE_STYLE,
        children=[
            html.Div(
                style=SHELL_STYLE,
                children=[
                    html.Div(
                        style=CARD_STYLE,
                        children=[
                            html.H1(APP_TITLE, style={"margin": "0 0 8px", "fontSize": "28px"}),
                            html.P(APP_SUBTITLE, style={"margin": "0 0 16px", "color": "#52616f"}),
                            html.H2(
                                "Artifact Validation Errors",
                                style={"fontSize": "18px", "margin": "0 0 10px"},
                            ),
                            html.P(
                                "The dashboard could not load required Notebook 07b artifacts.",
                                style={"margin": "0 0 10px"},
                            ),
                            html.Ul([html.Li(error) for error in errors]),
                        ],
                    )
                ],
            )
        ],
    )


def build_layout(artifacts: dict[str, pd.DataFrame | list[str]]) -> html.Div:
    """Build the Dash layout from already-loaded artifacts."""
    errors = artifacts.get("_errors", [])
    if errors:
        return _error_layout([str(error) for error in errors])

    scorecard = artifacts["scorecard"]  # type: ignore[index]
    dislocation_scores = artifacts["dislocation_scores"]  # type: ignore[index]
    diagnostics = artifacts["rolling_pca_diagnostics"]  # type: ignore[index]
    gap_table = artifacts["methodology_gap_table"]  # type: ignore[index]
    assert isinstance(scorecard, pd.DataFrame)
    assert isinstance(dislocation_scores, pd.DataFrame)
    assert isinstance(diagnostics, pd.DataFrame)
    assert isinstance(gap_table, pd.DataFrame)

    default_assets = latest_top_abs_dislocation_assets(scorecard, n=5)
    asset_options = _dropdown_options(dislocation_scores.get("asset", scorecard["asset"]))
    asset_class_values = _all_values(scorecard["asset_class"]) if "asset_class" in scorecard else []
    regime_values = _all_values(scorecard["dominant_regime"]) if "dominant_regime" in scorecard else []
    diagnostic_values = (
        _all_values(scorecard["diagnostic_label"]) if "diagnostic_label" in scorecard else []
    )
    top_max = max(10, min(30, len(scorecard))) if not scorecard.empty else 10
    gap_columns = [
        col
        for col in ["methodology_element", "availability_in_repo", "07b_v1_treatment"]
        if col in gap_table.columns
    ]

    return html.Div(
        style=PAGE_STYLE,
        children=[
            html.Div(
                style=SHELL_STYLE,
                children=[
                    html.Div(
                        style=HEADER_STYLE,
                        children=[
                            html.H1(
                                APP_TITLE,
                                style={
                                    "margin": "0 0 6px",
                                    "fontSize": "32px",
                                    "lineHeight": "1.2",
                                    "color": "#ffffff",
                                },
                            ),
                            html.P(
                                APP_SUBTITLE,
                                style={
                                    "margin": "0 0 14px",
                                    "fontSize": "15px",
                                    "color": "#d7e2ee",
                                },
                            ),
                            html.P(
                                ARTIFACT_ONLY_NOTE,
                                style={
                                    "display": "inline-block",
                                    "margin": "0 0 14px",
                                    "padding": "7px 10px",
                                    "borderRadius": "6px",
                                    "backgroundColor": "rgba(255, 255, 255, 0.08)",
                                    "border": "1px solid rgba(255, 255, 255, 0.13)",
                                    "fontSize": "13px",
                                    "lineHeight": "1.4",
                                    "color": "#e8eef6",
                                },
                            ),
                            html.P(
                                DISCLAIMER,
                                style={
                                    "margin": 0,
                                    "fontSize": "12.5px",
                                    "lineHeight": "1.5",
                                    "color": "#b9c6d4",
                                },
                            ),
                        ],
                    ),
                    _kpi_cards(scorecard),
                    html.Div(
                        style=CARD_STYLE,
                        children=[
                            html.H2("Controls", style=SECTION_TITLE_STYLE),
                            html.Div(
                                style=CONTROL_GRID_STYLE,
                                children=[
                                    _control(
                                        "Asset class",
                                        dcc.Dropdown(
                                            id="asset-class-filter",
                                            options=[
                                                {"label": "All asset classes", "value": "__ALL__"}
                                            ]
                                            + _dropdown_options(scorecard["asset_class"]),
                                            value=["__ALL__"],
                                            multi=True,
                                            clearable=False,
                                        ),
                                    ),
                                    _control(
                                        "Regime",
                                        dcc.Dropdown(
                                            id="regime-filter",
                                            options=[{"label": "All regimes", "value": "__ALL__"}]
                                            + _dropdown_options(regime_values),
                                            value=["__ALL__"],
                                            multi=True,
                                            clearable=False,
                                            disabled=not bool(regime_values),
                                        ),
                                    ),
                                    _control(
                                        "Diagnostic label",
                                        dcc.Dropdown(
                                            id="diagnostic-filter",
                                            options=[
                                                {"label": "All diagnostic labels", "value": "__ALL__"}
                                            ]
                                            + _dropdown_options(diagnostic_values),
                                            value=["__ALL__"],
                                            multi=True,
                                            clearable=False,
                                            disabled=not bool(diagnostic_values),
                                        ),
                                    ),
                                    _control(
                                        "Top N by absolute dislocation",
                                        dcc.Slider(
                                            id="top-n-filter",
                                            min=5,
                                            max=top_max,
                                            step=1,
                                            value=min(10, top_max),
                                            marks={
                                                5: "5",
                                                min(10, top_max): str(min(10, top_max)),
                                                top_max: str(top_max),
                                            },
                                            tooltip={"placement": "bottom", "always_visible": False},
                                        ),
                                    ),
                                    html.Div(
                                        style={"gridColumn": "1 / -1"},
                                        children=[
                                            html.Label("Selected assets", style=LABEL_STYLE),
                                            dcc.Dropdown(
                                                id="asset-selector",
                                                options=asset_options,
                                                value=default_assets,
                                                multi=True,
                                                clearable=True,
                                            ),
                                        ],
                                    ),
                                ],
                            ),
                        ],
                    ),
                    html.Div(
                        style=CARD_STYLE,
                        children=[
                            html.H2("Latest Scorecard", style=SECTION_TITLE_STYLE),
                            html.Div(
                                "Diagnostic scorecard view; values are loaded from saved artifacts.",
                                style={
                                    "fontSize": "12.5px",
                                    "color": "#64748b",
                                    "margin": "-6px 0 12px",
                                },
                            ),
                            html.Div(id="scorecard-table-container"),
                        ],
                    ),
                    html.Div(
                        style={
                            "display": "grid",
                            "gridTemplateColumns": "repeat(auto-fit, minmax(420px, 1fr))",
                            "gap": "18px",
                        },
                        children=[
                            html.Div(
                                style=CARD_STYLE,
                                children=[
                                    dcc.Graph(
                                        id="dislocation-bar",
                                        config=GRAPH_CONFIG,
                                        figure=make_dislocation_bar(scorecard, 10),
                                    )
                                ],
                            ),
                            html.Div(
                                style=CARD_STYLE,
                                children=[
                                    dcc.Graph(
                                        id="dislocation-momentum-scatter",
                                        config=GRAPH_CONFIG,
                                        figure=make_dislocation_momentum_scatter(scorecard),
                                    )
                                ],
                            ),
                        ],
                    ),
                    html.Div(
                        style=CARD_STYLE,
                        children=[
                            dcc.Graph(
                                id="dislocation-timeseries",
                                config=GRAPH_CONFIG,
                                figure=make_dislocation_timeseries(
                                    dislocation_scores, default_assets
                                ),
                            )
                        ],
                    ),
                    html.Div(
                        style=CARD_STYLE,
                        children=[
                            dcc.Graph(
                                id="rolling-pca-diagnostics",
                                config=GRAPH_CONFIG,
                                figure=make_rolling_pca_diagnostics(diagnostics),
                            )
                        ],
                    ),
                    html.Div(
                        style=CARD_STYLE,
                        children=[
                            html.H2("Methodology Gap Disclosure", style=SECTION_TITLE_STYLE),
                            html.P(
                                GAP_NOTE,
                                style={
                                    "fontSize": "13px",
                                    "lineHeight": "1.5",
                                    "color": "#52616f",
                                    "margin": "0 0 12px",
                                },
                            ),
                            _small_table(gap_table[gap_columns] if gap_columns else gap_table),
                        ],
                    ),
                ],
            )
        ],
    )


def _normalize_filter(values: list[str] | str | None) -> list[str] | None:
    if values is None:
        return None
    if isinstance(values, str):
        values = [values]
    if "__ALL__" in values:
        return None
    return values


ARTIFACTS = load_artifacts()
app = Dash(__name__, title=APP_TITLE)
app.layout = build_layout(ARTIFACTS)


@app.callback(
    Output("scorecard-table-container", "children"),
    Output("dislocation-bar", "figure"),
    Output("dislocation-momentum-scatter", "figure"),
    Input("asset-class-filter", "value"),
    Input("regime-filter", "value"),
    Input("diagnostic-filter", "value"),
    Input("top-n-filter", "value"),
)
def update_scorecard_views(
    asset_classes: list[str] | str | None,
    regimes: list[str] | str | None,
    diagnostic_labels: list[str] | str | None,
    top_n: int,
) -> tuple[dash_table.DataTable, go.Figure, go.Figure]:
    scorecard = ARTIFACTS.get("scorecard", pd.DataFrame())
    assert isinstance(scorecard, pd.DataFrame)
    filtered = filter_scorecard(
        scorecard,
        _normalize_filter(asset_classes),
        _normalize_filter(regimes),
        _normalize_filter(diagnostic_labels),
    )
    return (
        _scorecard_table(filtered),
        make_dislocation_bar(filtered, int(top_n or 10)),
        make_dislocation_momentum_scatter(filtered),
    )


@app.callback(
    Output("dislocation-timeseries", "figure"),
    Input("asset-selector", "value"),
)
def update_dislocation_timeseries(selected_assets: list[str] | str | None) -> go.Figure:
    dislocation_scores = ARTIFACTS.get("dislocation_scores", pd.DataFrame())
    assert isinstance(dislocation_scores, pd.DataFrame)
    if isinstance(selected_assets, str):
        selected_assets = [selected_assets]
    return make_dislocation_timeseries(dislocation_scores, selected_assets or [])


if __name__ == "__main__":
    app.run(debug=True)
